### ISSUE TITLE
Exception possibly due to cache backend.

### ISSUE THREAD

**Issue by mathewknoop** [sh4nks/flask-caching#148]
I am getting the following error. Despite this the cache seems to be performing as expected.

cache = Cache(config={'CACHE_TYPE': 'filesystem','CACHE_DIR':'/tmp/'})
cache.init_app(application)

using the following decorator to wrap my functions.

@cache.cached(timeout=920)

Here is the error from gunicorn's stdout.

Exception possibly due to cache backend.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/flask_caching/__init__.py", line 443, in decorated_function
    timeout=decorated_function.cache_timeout,
  File "/opt/conda/lib/python3.7/site-packages/flask_caching/backends/filesystem.py", line 187, in set
    pickle.dump(value, f, pickle.HIGHEST_PROTOCOL)
TypeError: cannot serialize '_io.BufferedReader' object

**Comment by sh4nks** [comment]
Can't reproduce.
