### ISSUE TITLE
TypeError: cannot serialize '_io.BufferedReader' object

### ISSUE THREAD

**Issue by fili** [sh4nks/flask-caching#167]
FYI got this error today while running on App Engine Standard while using the filesystem as CACHE_TYPE with /tmp as CACHE_DIR 

```
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask_caching/__init__.py", line 443, in decorated_function
    timeout=decorated_function.cache_timeout,
  File "/env/lib/python3.7/site-packages/flask_caching/backends/filesystem.py", line 187, in set
    pickle.dump(value, f, pickle.HIGHEST_PROTOCOL)
TypeError: cannot serialize '_io.BufferedReader' object
```

**Comment by sh4nks** [comment]
Unfortunately I can't reproduce this error.

**Comment by lyknode** [comment]
Hi @sh4nks,

I'm having the same issue as @fili, when using flask's [send_from_directory](https://flask.palletsprojects.com/en/1.1.x/api/#flask.send_from_directory) method.

You can reproduce with the following code:
```python
from flask import Flask, send_from_directory
from flask_caching import Cache
from os.path import dirname, basename

app = Flask(__name__)
cache = Cache(app, config={'CACHE_TYPE': 'simple'})


@app.route('/')
@cache.cached()
def root():
    return send_from_directory(dirname(__file__), basename(__file__))
```

**Comment by gergelypolonkai** [comment]
I’m not completely sure this can (and should) be solved within Flask-Caching. We either cache the full result of the `send_from_directory`, this way effectively removing a potential other cache layer, or decide not to cache `_io.BufferedReader` and call the cached function (`root()` in @lyknode ’s case), overriding the developer’s intent (dev says cache, cache always says it’s not in the cache).

**Comment by Tim-Schwalbe** [comment]
same issue here...

**Comment by lyknode** [comment]
@gergelypolonkai, I would be fine with either solution (caching or not caching). With maybe a preference for not caching `_io.BufferedReader ` since, as you said that might invalid other type of cache and serving big files would eat up all the cache memory.

Either way, the real problem here is the Exception that prevent the request from serving the file.

My issue is also that I cannot just remove the `@cached()` from the route because my real use case is actually serving a "cachable" resource or a `_io.BufferedReader ` depending on the request parameter.

**Comment by Tim-Schwalbe** [comment]
I solved it by just using `pip install cachetools`
And then extracting the part I want to cache to a function and do simple caching on that function:


```
@cached(cache=TTLCache(maxsize=300, ttl=60))
def download_doc(doc_name):
            client = storage.Client.from_service_account_json("gcs-api-sa.json")
            bucket = client.bucket("spl_docs")
            blob = bucket.blob(doc_name)
            blob.download_to_filename(curr_work_dir+'/'+doc_name)
```

**Comment by fili** [comment]
FYI today I got this error with FileSystemCache and SimpleCache on Google Cloud Run with Docker (python3.8-slim-buster)

```
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/flask_caching/__init__.py", line 479, in decorated_function
    self.cache.set(
  File "/env/lib/python3.8/site-packages/flask_caching/backends/filesystemcache.py", line 219, in set
    pickle.dump(value, f, pickle.HIGHEST_PROTOCOL)
TypeError: cannot pickle '_io.BufferedReader' object
```

**Comment by loleg** [comment]
This is still an issue (python 3.10, Flask-Caching 2.0.2, Simple).

**Comment by skywarspro15** [comment]
Can confirm, still an issue using FileSystemCache (Python 3.10.11, Flask-Caching 2.0.2) 
![image](https://github.com/pallets-eco/flask-caching/assets/86519653/cab65e1c-1047-45b2-bf0f-e86f6e747489)

**Comment by loleg** [comment]
Still pops up (Python 3.12.11, Flask-Caching 2.3.1) as follows:

```
TypeError: cannot pickle 'BufferedReader' instances
Exception possibly due to cache backend.
Traceback (most recent call last):
|   File "/usr/local/lib/python3.12/site-packages/flask_caching/__init__.py", line 435, in decorated_function
|     self.cache.set(
|   File "/usr/local/lib/python3.12/site-packages/cachelib/simple.py", line 76, in set
|     self._cache[key] = (expires, self.serializer.dumps(value))
|                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/usr/local/lib/python3.12/site-packages/cachelib/serializers.py", line 43, in dumps
|     serialized = pickle.dumps(value, protocol)
|                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by john0isaac** [comment]
There are two solutions to this issue either use `freeze()` function from `werkzeug` or read the stream in memory and pickle the read file not the stream.
You can't pickle streams and what `send_from_directory` returns is a stream.
`werkzeug` already gives you picklable objects using it's `freeze` function on the response.

Another solution would be to write your own serializer that handles pickling streams, I did both solutions in the code sample below to demonstrate how that might work.

In the first approach, we override the default serializer provided by CacheLib with our own serializer that can handle pickling stream, the approach used to handle pickling streams is reading the stream in memory as bytes then pickling that in the cache and returning it again when needed.
The function `_materialize_streams` recursively looks for the object that has a `read` function then reads it and returns it to be pickled.

In the second approach, it's a one line change use `response.freeze()` before returning from the endpoint. 

```py
import io
import pickle
import typing as _t
from os.path import basename
from os.path import dirname

from flask import Flask
from flask import send_from_directory
from flask_caching import Cache

from cachelib.serializers import SimpleSerializer

app = Flask(__name__)
serializer_cache = Cache(app, config={"CACHE_TYPE": "simple"})
normal_cache = Cache(app, config={"CACHE_TYPE": "simple"})

class _PicklableStream:
    """
    Picklable wrapper for file like objects.
    """
    def __init__(self, data: bytes):
        self._data = data
        self._buf = io.BytesIO(data)

    def read(self, size: int = -1) -> bytes:
        return self._buf.read(size)

    def __getstate__(self):
        return {"data": self._data}

    def __setstate__(self, state):
        self.__init__(state["data"])


class CustomSerializer(SimpleSerializer):
    """
    Custom serializer that handles pickling files streams.

    Read the file stream into memory and store it as bytes.
    """

    def _materialize_streams(self, value, _seen=None):
        _seen = _seen if _seen is not None else set()
        if id(value) in _seen:
            return value
        _seen.add(id(value))
        if hasattr(value, "read") and callable(value.read):
            return _PicklableStream(value.read())
        if hasattr(value, "__dict__"):
            for attr, attr_value in vars(value).items():
                if hasattr(attr_value, "read") and callable(attr_value.read):
                    setattr(value, attr, _PicklableStream(attr_value.read()))
                else:
                    self._materialize_streams(attr_value, _seen)
        return value

    def dumps(
        self, value: _t.Any, protocol: int = pickle.HIGHEST_PROTOCOL
    ) -> bytes | None:
        try:
            serialized = pickle.dumps(value, protocol)
        except TypeError:
            materialized = self._materialize_streams(value)
            return pickle.dumps(materialized, protocol)
        except (pickle.PickleError, pickle.PicklingError) as e:
            self._warn(e)
            return None
        return serialized

serializer_cache.cache.serializer = CustomSerializer()

@app.route("/serializer-override")
@serializer_cache.cached()
def root():
    return send_from_directory(dirname(__file__), basename(__file__))

@app.route("/freeze-werkzeug")
@normal_cache.cached()
def freeze_werkzeug():
    response = send_from_directory(dirname(__file__), basename(__file__))
    # Freeze makes the response object picklable.
    response.freeze()
    return response

if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5001)
```

**Comment by sh4nks** [comment]
I updated the documentation and added @john0isaac example serializer
