### ISSUE TITLE
KeyError: 'cache'

### ISSUE THREAD

**Issue by VedAustin** [sh4nks/flask-caching#175]
I have 2 files:
1st file: knn_test.py
```
import logging
from flask_caching import Cache
import testing_cache

app = testing_cache.app
cache = Cache(config={
                     'CACHE_TYPE': 'redis',
                     'CACHE_REDIS_URL': 'redis://127.0.0.1:6379'
                    })
cache.init_app(app)
logging.basicConfig(level=logging.DEBUG)

@cache.cached(timeout=60*15, key_prefix='knn_model_test')
def knn_model():
    logging.debug("Inside knn_model")
    model_arr = [1, 3]
    return model_arr

```

2nd file:
testing_cache.py
```
import knn_test
from flask import Flask
from flask_caching import Cache
import logging

logging.basicConfig(level=logging.DEBUG)

app = Flask(__name__)


@app.route('/')
def test():
    knn_test.knn_model()
    return "Successful"


if __name__ == '__main__':
    app.run(debug=True, host='localhost', port=8051)
```

When I call the api (for example from postman for example), I get the following error message:
```
ERROR:flask_caching:Exception possibly due to cache backend.
Traceback (most recent call last):
  File "/ENVs/dash-test/lib/python3.7/site-packages/flask_caching/__init__.py", line 412, in decorated_function
    rv = self.cache.get(cache_key)
  File "/ENVs/dash-test/lib/python3.7/site-packages/flask_caching/__init__.py", line 239, in cache
    return app.extensions["cache"][self]
KeyError: 'cache'
```

However when I have everything in a single file, it works fine:
```
from flask import Flask
from flask_caching import Cache
import logging

logging.basicConfig(level=logging.DEBUG)

app = Flask(__name__)

cache = Cache(config={
                     'CACHE_TYPE': 'redis',
                     'CACHE_REDIS_URL': 'redis://127.0.0.1:6379'
                    })

cache.init_app(app)

@cache.cached(timeout=60*15, key_prefix='knn_model_test')
def knn_model():
    logging.debug("Inside knn_model")
    model_arr = [1, 3]
    return model_arr


@app.route('/')
def test():
    knn_model()
    return "Successful"


if __name__ == '__main__':
    app.run(debug=True, host='localhost', port=8051)

```

Any idea what is going on?

**Comment by gergelypolonkai** [comment]
Hello,

the Cache instance you use is bound to the app created in knn_test.py, but
you want to use it through the app created in testing_cache.py.

You should either import app from knn_test instead of creating a separate
one in testing_cache, or create a separate cache instance in testing_cache.
You might try rebinding knn_test.cache to the other app with
cache.init_app(), but it might have unforseen consequences.

Best,
Gergey

**Comment by VedAustin** [comment]
Hi Gergey,

Thank you so much for your help in understanding this! Based on what you said, I created a standalone file, app_test.py:

```
from flask import Flask

app_test = Flask(__name__)
```
And from above imported the file into other apps like below:
knn_test.py
```
import logging
from flask_caching import Cache
from app_test import app_test

cache = Cache(app_test, config={
                     'CACHE_TYPE': 'redis',
                     'CACHE_REDIS_URL': 'redis://127.0.0.1:6379'
                    })

logging.basicConfig(level=logging.DEBUG)


@cache.cached(timeout=60*15, key_prefix='knn_model_test')
def knn_model():
    logging.debug("Inside knn_model")
    model_arr = [1, 3]
    return model_arr
```

I can also have other files like lr_test.py:
```

    import logging

    from flask_caching import Cache
    from app_test import app_test
    
    cache = Cache(app_test, config={
                         'CACHE_TYPE': 'redis',
                         'CACHE_REDIS_URL': 'redis://127.0.0.1:6379'
                        })
    
    logging.basicConfig(level=logging.DEBUG)
    
    
    @cache.cached(timeout=60*15, key_prefix='lr_model_test')
    def lr_model():
        logging.debug("Inside knn_model")
        model_arr = [1, 3]
        return model_arr
```
And finally can run a Flask app, testing_cache.py like this:
```
from knn_test import knn_model
from lr_test import lr_model

from flask_caching import Cache
import logging
from app_test import app_test

logging.basicConfig(level=logging.DEBUG)

cache = Cache(app_test, config={
                     'CACHE_TYPE': 'redis',
                     'CACHE_REDIS_URL': 'redis://127.0.0.1:6379'
                    })

@app_test.route('/knn')
def test1():
    knn_model()

    return "Successful"


@app_test.route('/lr')
def test2():
    lr_model()
    return "Successful"


if __name__ == '__main__':
    app_test.run(debug=True, host='localhost', port=8051)

```

The above set up works great. Thank you once again for your input on this! Much appreciated
