### ISSUE TITLE
has no attribute 'has'

### ISSUE THREAD

**Issue by teamlyzer** [sh4nks/flask-caching#178]
Hello,

I would like to understand the has()

```
self._read_clients.get(self._get_prefix() + key)
self._read_clients.exists(self._get_prefix() + key)
```
The get runs fine but the second I get 'Cache' object has no attribute 'has'. From docs "This method is optional and may not be implemented on all caches."

What this means exactly? Since the EXISTS cmd runs fine:

127.0.0.1:6379[10]> EXISTS fcache_template_fragment_cache_all_overall
(integer) 1

**Comment by gergelypolonkai** [comment]
Please copy the whole backtrace here, otherwise it’s hard to debug, let alone fixi this issue.

**Comment by teamlyzer** [comment]
Here is the backtrace 

```
Traceback (most recent call last):
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/werkzeug/middleware/proxy_fix.py", line 228, in __call__
    return self.app(environ, start_response)
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/myproject/app/companies/views.py", line 114, in ranking
    if cache.has("_template_fragment_cache_"+filter_size+"_"+criteria) is None:
AttributeError: 'Cache' object has no attribute 'has'
```

**Comment by sh4nks** [comment]
This method is not directly implemented in the ``Cache`` class. You have to go an layer deeper - 
``cache.cache.has()`` should work.

**Comment by teamlyzer** [comment]
@sh4nks perfect. Thank you
