### ISSUE TITLE
Various errors with pylibmc backend

### ISSUE THREAD

**Issue by Berserker66** [sh4nks/flask-caching#193]
So, in my dev environment I use a simple waitress launcher, production runs gunicorn+nginx. This is from the dev environment.
I tried switching from simple to memcached to better work with the multiple processes the gunicorn+nginx combo brings and well, here's some errors:

```
ERROR:waitress:Exception while serving /TicketMonitor/GeschÃ¤ftsfÃ¼hrung
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/waitress/channel.py", line 350, in service
    task.service()
  File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 171, in service
    self.execute()
  File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 441, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_caching/__init__.py", line 883, in decorated_function
    rv = self.cache.get(cache_key)
  File "/usr/local/lib/python3.7/dist-packages/flask_caching/backends/memcache.py", line 110, in get
    return self._client.get(key)
pylibmc.Error: error 15 from memcached_get(flask_cache_YvIahY8bQRO5I5koWm/M)
```
```
ERROR:waitress:Exception while serving /TicketMonitor/Honorar+
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/waitress/channel.py", line 350, in service
    task.service()
  File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 171, in service
    self.execute()
  File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 441, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_caching/__init__.py", line 914, in decorated_function
    timeout=decorated_function.cache_timeout,
  File "/usr/local/lib/python3.7/dist-packages/flask_caching/backends/memcache.py", line 141, in set
    return self._client.set(key, value, timeout)
pylibmc.Error: error 21 from memcached_set
```
```
ERROR:waitress:Exception while serving /TicketMonitor/Hotline
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/waitress/channel.py", line 350, in service
    task.service()
  File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 171, in service
    self.execute()
  File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 441, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_caching/__init__.py", line 868, in decorated_function
    f, *args, **kwargs
  File "/usr/local/lib/python3.7/dist-packages/flask_caching/__init__.py", line 643, in make_cache_key
    f, args=args, timeout=_timeout, forced_update=forced_update
  File "/usr/local/lib/python3.7/dist-packages/flask_caching/__init__.py", line 593, in _memoize_version
    version_data_list = list(self.cache.get_many(*fetch_keys))
  File "/usr/local/lib/python3.7/dist-packages/flask_caching/backends/memcache.py", line 144, in get_many
    d = self.get_dict(*keys)
  File "/usr/local/lib/python3.7/dist-packages/flask_caching/backends/memcache.py", line 126, in get_dict
    rv[key_mapping[key]] = value
KeyError: b'flask_cache_app.stats_specific_memver'
```
```
ERROR:waitress:Exception while serving /TicketMonitor/Panda
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/waitress/channel.py", line 350, in service
    task.service()
  File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 171, in service
    self.execute()
  File "/usr/local/lib/python3.7/dist-packages/waitress/task.py", line 441, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_caching/__init__.py", line 914, in decorated_function
    timeout=decorated_function.cache_timeout,
  File "/usr/local/lib/python3.7/dist-packages/flask_caching/backends/memcache.py", line 141, in set
    return self._client.set(key, value, timeout)
pylibmc.SocketCreateError: error 11 from memcached_set
```

I've also seen error code 1 and 3.

**Comment by sh4nks** [comment]
Hi, could you provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by Berserker66** [comment]
Not easily as this is a closed source commercial application and we've now made the decision not to use this system at all. So, I'd have to use my own free time to get you that and that's currently looking rather sparse. I may be able to do so in a few days' time.
