### ISSUE TITLE
Craches on caching

### ISSUE THREAD

**Issue by nikonov91-dev** [sh4nks/flask-caching#249]
I started from scratch the project but get this error
```
/usr/local/bin/python3.8 "/Users/alexmotorniyg/Library/Application Support/JetBrains/IntelliJIdea2020.3/plugins/python/helpers/pydev/pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 51296 --file /Users/alexmotorniyg/Documents/od-platform/app.py
Connected to pydev debugger (build 203.7148.57)
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app "app" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Debugger is active!
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Exception possibly due to cache backend.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask_caching/__init__.py", line 451, in decorated_function
    rv = self.cache.get(cache_key)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask_caching/__init__.py", line 259, in cache
    return app.extensions["cache"][self]
KeyError: <flask_caching.Cache object at 0x7fbec92bfac0>
127.0.0.1 - - [21/Apr/2021 14:02:42] "GET /test HTTP/1.1" 200 -
```

When I try to cache a simple function:

The structure of my app is:
```
| - app.py
| - api
      | - __init__.py
      | - main_api.py
``` 

So first I initiate the app.py
```
from flask import Flask
from flask_caching import Cache


app = Flask(__name__)
cache = Cache(app, config={'CACHE_TYPE': 'simple'})


from api import api as api_bp
app.register_blueprint(api_bp)
```

Second I create the main_api.py
```
from flask import jsonify
from . import api
from app import cache
import random


@api.route('/test', methods=['GET', 'POST'])
@cache.cached(timeout=2)
def rand():
  return jsonify(random.randint(1, 10))
```
__init__.py is simple as abc
```
from flask import Blueprint

api = Blueprint('api', __name__)
from . import main_api
```

Used Python3.8 and Installed dependencies
```
click==7.1.2
Flask==1.1.2
Flask-Caching==1.10.1
itsdangerous==1.1.0
Jinja2==2.11.3
MarkupSafe==1.1.1
Werkzeug==1.0.1
```

**Comment by gergelypolonkai** [comment]
I can’t reproduce this with the code you provided (and an extra `__init__.py` under `api` you forgot to show us).

Can you tell how you start the Flask app?

**Comment by nikonov91-dev** [comment]
I installed the app from scratch and updated the issue, can you check it please ?

**Comment by nikonov91-dev** [comment]
Hi, is there any updates?

**Comment by gergelypolonkai** [comment]
After creating all the files and installing all the packages you mention, i start the app like this:

```
env FLASK_APP=app:app flask run
```

Is it the same as you do?

For me, it works just fine, with any Python version from 3.6 to 3.9

**Comment by nikonov91-dev** [comment]
Yea, you're right, if I run in the shell, not in Intellij Idea application run, it does work without any crash.
But my app is running fine being configured and ran in Intellij Idea using the bunch of other libraries without any problem:
```
alembic==1.5.7
argon2-cffi==20.1.0
azure-core==1.10.0
azure-storage-blob==12.7.0
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
click==7.1.2
cryptography==3.3.1
Flask==1.1.2
Flask-Argon2==0.2.0.0
Flask-Cors==3.0.10
Flask-JWT-Extended==4.1.0
Flask-Migrate==2.7.0
Flask-SQLAlchemy==2.5.1
greenlet==1.0.0
idna==2.10
isodate==0.6.0
itsdangerous==1.1.0
Jinja2==2.11.2
Mako==1.1.4
MarkupSafe==1.1.1
msrest==0.6.19
oauthlib==3.1.0
psycopg2-binary==2.8.6
pycparser==2.20
PyJWT==2.0.1
python-dateutil==2.8.1
python-editor==1.0.4
requests==2.25.1
requests-oauthlib==1.3.0
six==1.15.0
SQLAlchemy==1.4.1
urllib3==1.26.2
Werkzeug==1.0.1
```
May be you can try to run it with Intellij Idea by yourself?

My configs are:
```
script path: /Users/username/Documents/cache-test/app.py
environmental vars: 
FLASK_APP=app:create_app
FLASK_ENV=development
interpreter options: use specified interpreter: Python 3.8 (/usr/local/bin/python3.8
working directory: : /Users/username/Documents/cache-test
```
![image](https://user-images.githubusercontent.com/31586394/116983741-25f7b600-acd3-11eb-9adf-167ba0916ab7.png)

**Comment by sh4nks** [comment]
Sorry but I don't use Intellij and as such I can't help you with your problem. Maybe someone else can.
