### ISSUE TITLE
Multiple errors (with memcached)

### ISSUE THREAD

**Issue by ivanionut** [sh4nks/flask-caching#415]
Hello,
occasionally Sentry catches these errors and I don't understand what the problem can be. 

Can anyone give me some suggestions? 
Thank you!

```
python        3.10.6
memcached     1.6.14
flask         2.2.2
flask-caching 2.0.1
cachelib      0.9.0
```
![1](https://user-images.githubusercontent.com/2210744/203287554-d1c16f35-355f-4bbe-bd65-f786db8e3d30.png)

![2](https://user-images.githubusercontent.com/2210744/203287580-970d4673-8a6f-4296-a73d-2af80dee6645.png)

![3](https://user-images.githubusercontent.com/2210744/203287672-eef538d4-df8f-420e-b8b8-bdaceedde729.png)

![4](https://user-images.githubusercontent.com/2210744/203287701-20d8c2f6-73cb-4e1a-b8d6-ecc4a12fc3e4.png)

**Comment by rubybui** [comment]
still having issue. Tried all memcache plugin

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — without more info this one is hard to act on, so it might be a candidate for closure unless you can share a repro.

Evidence:
- The issue body has three screenshots but no text-form traceback, no minimal reproducer, and no breakdown of which call site triggers each error (the package versions you cited — flask 2.2.2, flask-caching 2.0.1, cachelib 0.9.0 — are >2 years old as of writing).
- [`CONTRIBUTING.md`](https://github.com/pallets-eco/flask-caching/blob/main/CONTRIBUTING.md#reporting-issues) asks for a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and the full traceback as text so it can be searched and copied. The screenshots don't give the maintainers enough to diagnose.
- Most "occasional memcached errors via Sentry" reports historically resolve as either (1) the memcached client crashing on `set` with too-large payloads (resolve by tweaking `CACHE_THRESHOLD` / payload size), or (2) network blips on the client driver.

If you can still reproduce on `>=2.4.0`, please share:
- a copy-pasteable traceback (text),
- the route/function decorator,
- the cache config dict,
- the approximate cached payload size.

Without those, would you mind closing this out? Happy to reopen as soon as a repro lands.

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually.*

**Comment by john0isaac** [comment]
3 out of the 4 issues you attached says that your `memcached` server is not available.

Only one issue "**cannot serialize '_io.BufferedReader' object**" flags a problem that is solvable if you follow this example here https://github.com/pallets-eco/flask-caching/issues/167#issuecomment-5207693978

You attached 4 screenshots only one of them is an actual issue the rest is your `memcached` server not available as the errors state in the screenshot "**ServerDown**" "**SocketCreateError**" "**No Servers**"

@sh4nks you can close this issue.

**Comment by ivanionut** [comment]
@john0isaac 

Hi, I keep getting similar errors ALL THE TIME even today and it's not a problem with the memcached server.

Some examples:

```
Traceback (most recent call last):
  File "flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "santi/routes.py", line 60, in santo
    cache.set(f"santo_by_slug_{slug}", rc.santo, timeout=60 * 60)
  File "__init__.py", line 193, in set
    return self.cache.set(*args, **kwargs)
  File "cachelib/memcached.py", line 114, in set
    return bool(self._client.set(key, value, timeout))
Error: error 21 from memcached_set
```

Others:

```
Traceback (most recent call last):
  File "__init__.py", line 375, in decorated_function
    rv = self.cache.get(cache_key)
  File "cachelib/memcached.py", line 84, in get
    return self._client.get(key)
Error: error 15 from memcached_get(flask_cache_/pietro-crisologobcd)
```

And so on:

```
Traceback (most recent call last):
  File "__init__.py", line 375, in decorated_function
    rv = self.cache.get(cache_key)
  File "cachelib/memcached.py", line 84, in get
    return self._client.get(key)
Error: error 15 from memcached_get(flask_cache_/pietro-crisologobcd)
```

So there are clearly some serious problems with the cache extension.

**Comment by john0isaac** [comment]
@ivanionut Thanks for responding so quick and sorry for the delay in getting to your problem.
The places where your errors happen are not in cachelib or in flask-caching they are happening from the underlying memcache client we use.

Could you please let me know the version of flask-caching, cachelib you are currently using?
Also which memcached client do you use pylibmc, libmc, python-memcached…?

**Comment by ivanionut** [comment]
```
memcached     1.6.14
flask         2.2.2
flask-caching 2.0.1
cachelib      0.9.0
```

**Comment by john0isaac** [comment]
You didn't share the most important thing which I asked about separately as it's the key to figuring out why you are getting all of these errors.

I assumed you are using `pylibmc` and will answer accordingly.
I was able to replicate your errors locally with docker setup and apache bench.
I guess you are getting a lot of the below errors.
The main reason you get these errors was because the usage of `pylibmc` in cacehlib prior to version 0.15.0 was not thread-safe.
In version 0.15.0, I added thread-safety to `pylibmc`. To simplify what's added in CacheLib 0.15.0, if you are running a multithreaded application (like flask app with multiple threads) any thread may access information from other threads resulting in the errors you are seeing.

After upgrading CacheLib locally and running the benchmarks again I got 0 errors in the terminal.
In the same release 0.15.0 we also dropped support for python 3.10 so you will also need to upgrade your python version to 3.11.

To sum up:

- Upgrade python to 3.11
- Upgrade CacheLib to 0.15.0 or even better 0.15.4 (latest)

All your issues will be resolved.
cc: @rubybui you should do that too since it will resolve your issues.

```sh
caching-app  | [2026-08-14 09:51:47,461] ERROR in app: Exception on /santo/pietro-crisologo [GET]
caching-app  | Traceback (most recent call last):
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
caching-app  |     response = self.full_dispatch_request()
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
caching-app  |     rv = self.handle_user_exception(e)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
caching-app  |     rv = self.dispatch_request()
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
caching-app  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
caching-app  |   File "/app/main.py", line 13, in set_santo
caching-app  |     cache.set(f"santo_by_slug_{slug}", santo, timeout=60 * 60)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask_caching/__init__.py", line 198, in set
caching-app  |     return self.cache.set(*args, **kwargs)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/cachelib/memcached.py", line 114, in set
caching-app  |     return bool(self._client.set(key, value, timeout))
caching-app  | pylibmc.ProtocolError: error 8 from memcached_set: CONNECTION FAILURE
caching-app  | [2026-08-14 09:51:47,466] ERROR in app: Exception on /santo/pietro-crisologo [GET]
caching-app  | Traceback (most recent call last):
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
caching-app  |     response = self.full_dispatch_request()
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
caching-app  |     rv = self.handle_user_exception(e)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
caching-app  |     rv = self.dispatch_request()
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
caching-app  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
caching-app  |   File "/app/main.py", line 13, in set_santo
caching-app  |     cache.set(f"santo_by_slug_{slug}", santo, timeout=60 * 60)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask_caching/__init__.py", line 198, in set
caching-app  |     return self.cache.set(*args, **kwargs)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/cachelib/memcached.py", line 114, in set
caching-app  |     return bool(self._client.set(key, value, timeout))
caching-app  | pylibmc.ServerDown: error 47 from memcached_set: SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY
caching-app  | [2026-08-14 09:51:47,467] ERROR in app: Exception on /santo/pietro-crisologo/get[GET]
caching-app  | Traceback (most recent call last):
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
caching-app  |     response = self.full_dispatch_request()
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
caching-app  |     rv = self.handle_user_exception(e)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
caching-app  |     rv = self.dispatch_request()
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
caching-app  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
caching-app  |   File "/app/main.py", line 18, in get_santo
caching-app  |     value = cache.get(f"santo_by_slug_{slug}")
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask_caching/__init__.py", line 190, in get
caching-app  |     return self.cache.get(*args, **kwargs)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/cachelib/memcached.py", line 84, in get
caching-app  |     return self._client.get(key)
caching-app  | pylibmc.ServerDown: error 47 from memcached_get(flask_cache_santo_by_slug_pietro): SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY
caching-app  | [2026-08-14 09:51:47,471] ERROR in app: Exception on /santo/pietro-crisologo/get[GET]
caching-app  | Traceback (most recent call last):
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
caching-app  |     response = self.full_dispatch_request()
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
caching-app  |     rv = self.handle_user_exception(e)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
caching-app  |     rv = self.dispatch_request()
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
caching-app  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
caching-app  |   File "/app/main.py", line 18, in get_santo
caching-app  |     value = cache.get(f"santo_by_slug_{slug}")
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask_caching/__init__.py", line 190, in get
caching-app  |     return self.cache.get(*args, **kwargs)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/cachelib/memcached.py", line 84, in get
caching-app  |     return self._client.get(key)
caching-app  | pylibmc.SocketCreateError: error 11 from memcached_get(flask_cache_santo_by_slug_pietro)
caching-app  | [2026-08-14 09:51:47,472] ERROR in app: Exception on /santo/pietro-crisologo/get[GET]
caching-app  | Traceback (most recent call last):
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
caching-app  |     response = self.full_dispatch_request()
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
caching-app  |     rv = self.handle_user_exception(e)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
caching-app  |     rv = self.dispatch_request()
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
caching-app  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
caching-app  |   File "/app/main.py", line 18, in get_santo
caching-app  |     value = cache.get(f"santo_by_slug_{slug}")
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask_caching/__init__.py", line 190, in get
caching-app  |     return self.cache.get(*args, **kwargs)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/cachelib/memcached.py", line 84, in get
caching-app  |     return self._client.get(key)
caching-app  | pylibmc.Error: error 15 from memcached_get(flask_cache_santo_by_slug_pietro)
caching-app  | [2026-08-14 09:51:47,498] ERROR in app: Exception on /santo/pietro-crisologo [GET]
caching-app  | Traceback (most recent call last):
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
caching-app  |     response = self.full_dispatch_request()
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
caching-app  |     rv = self.handle_user_exception(e)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
caching-app  |     rv = self.dispatch_request()
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
caching-app  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
caching-app  |   File "/app/main.py", line 13, in set_santo
caching-app  |     cache.set(f"santo_by_slug_{slug}", santo, timeout=60 * 60)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask_caching/__init__.py", line 198, in set
caching-app  |     return self.cache.set(*args, **kwargs)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/cachelib/memcached.py", line 114, in set
caching-app  |     return bool(self._client.set(key, value, timeout))
caching-app  | pylibmc.ProtocolError: error 8 from memcached_set
caching-app  | [2026-08-14 09:51:47,498] ERROR in app: Exception on /santo/pietro-crisologo/get[GET]
caching-app  | Traceback (most recent call last):
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
caching-app  |     response = self.full_dispatch_request()
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
caching-app  |     rv = self.handle_user_exception(e)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
caching-app  |     rv = self.dispatch_request()
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
caching-app  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
caching-app  |   File "/app/main.py", line 18, in get_santo
caching-app  |     value = cache.get(f"santo_by_slug_{slug}")
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/flask_caching/__init__.py", line 190, in get
caching-app  |     return self.cache.get(*args, **kwargs)
caching-app  |   File "/app/.venv/lib/python3.10/site-packages/cachelib/memcached.py", line 84, in get
caching-app  |     return self._client.get(key)
caching-app  | pylibmc.Failure: error 1 from memcached_get(flask_cache_santo_by_slug_pietro): FAILURE
```

@sh4nks you can close. replicated the errors and replicated the fix so it's done now.

**Comment by sh4nks** [comment]
Awesome, thanks @john0isaac!
