### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '9'

### ISSUE THREAD

**Issue by fili** [sh4nks/flask-caching#93]
using blueprints, FileSystemCache on Google App Engine Standard Python3.7 and having the cache separate:

cache.py:
```
from flask_caching import Cache
cache = Cache()
```

config:
```
CACHE_CONFIG = {
    'CACHE_TYPE': 'filesystem',
    'CACHE_DIR': '/tmp',
    'CACHE_THRESHOLD': 1000,
    'CACHE_DEFAULT_TIMEOUT': 3600,
}
```

app.py:
```
app = Flask(__name__)
cache.init_app(app, config.CACHE_CONFIG)
app.config.from_object(flask_config)
```

blueprint:
```
from cache import cache 

@public.route('/<lang>/', methods=['GET'])
@cache.cached()
def page(lang):
    ...
```

Then getting this error:
```
ERROR:root:Traceback (most recent call last):
  File "/tmp/tmphwgdsy/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/tmphwgdsy/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/tmp/tmphwgdsy/lib/python3.6/site-packages/flask_caching/__init__.py", line 400, in decorated_function
    timeout=decorated_function.cache_timeout,
  File "/tmp/tmphwgdsy/lib/python3.6/site-packages/flask_caching/backends/filesystem.py", line 160, in set
    self._prune()
  File "/tmp/tmphwgdsy/lib/python3.6/site-packages/flask_caching/backends/filesystem.py", line 109, in _prune
    expires = pickle.load(f)
_pickle.UnpicklingError: invalid load key, '9'.
 ```

**Comment by sh4nks** [comment]
Can you reproduce this error without Google App Engine?

**Comment by sh4nks** [comment]
Can't reproduce on my local machine.

**Comment by dzpt** [comment]
same issue, it occurs sometimes, it's hard to reproduce

**Comment by gergelypolonkai** [comment]
@dzpt are you on GAE, too?

**Comment by dzpt** [comment]
@gergelypolonkai no, i was running it on localhost

**Comment by gergelypolonkai** [comment]
@dzpt is there a chance you can share with us the pickled value that made the pickle library throw up? Like reading it directly from from the cache or something. Iʼm trying to devise a failing test to this bug.

**Comment by anubhav-nd** [comment]
Hi,
Is there any update on this error? I too have been facing this but at random frequencies and unable to reproduce it consistently.
